// <auto-generated />
using System;
using CellTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CellTracker.Api.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008132908_Add_DbContext")]
    partial class Add_DbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cell_tracker")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CellTracker.Api.Models.OperatorTask.OperatorTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityGoal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OperatorTasks", "cell_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35031d70-8287-4bfe-bd63-05a816f44444"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample operator task",
                            Name = "Test Task",
                            QuantityGoal = 10
                        },
                        new
                        {
                            Id = new Guid("35031d70-8287-4bfe-bd63-05a816f44666"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sample operator task2",
                            Name = "Test Task2",
                            QuantityGoal = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
