// <auto-generated />
using System;
using CellTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CellTracker.Api.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127154034_OperatorTaskExtended")]
    partial class OperatorTaskExtended
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cell_tracker")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CellTracker.Api.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", "cell_tracker");
                });

            modelBuilder.Entity("CellTracker.Api.Auth.SiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginCode")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteUser", "cell_tracker");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("Cells", "cell_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Robotized soldering unit",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Soldering Cell",
                            OrdinalNumber = 1,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Optical quality inspection station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Inspection Cell",
                            OrdinalNumber = 2,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Box sealing and labeling unit1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packaging Cell1",
                            OrdinalNumber = 3,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Box sealing and labeling unit2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packaging Cell2",
                            OrdinalNumber = 4,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Box sealing and labeling unit3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packaging Cell3",
                            OrdinalNumber = 5,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Box sealing and labeling unit4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packaging Cell4",
                            OrdinalNumber = 6,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Preparation",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Solder Prep",
                            OrdinalNumber = 1,
                            ProductionLineId = new Guid("66666666-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("11111111-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wave solder station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Soldering",
                            OrdinalNumber = 2,
                            ProductionLineId = new Guid("66666666-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("11111111-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flux removal",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cleaning",
                            OrdinalNumber = 3,
                            ProductionLineId = new Guid("66666666-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chip placement",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pick&Place",
                            OrdinalNumber = 1,
                            ProductionLineId = new Guid("77777777-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Overheating tunnel",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Reflow",
                            OrdinalNumber = 2,
                            ProductionLineId = new Guid("77777777-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Optical inspection",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AOI",
                            OrdinalNumber = 3,
                            ProductionLineId = new Guid("77777777-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chassis assembly",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Housing Assembly",
                            OrdinalNumber = 1,
                            ProductionLineId = new Guid("88888888-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Firmware flashing",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Firmware Load",
                            OrdinalNumber = 2,
                            ProductionLineId = new Guid("88888888-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Final quality control",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Final QC",
                            OrdinalNumber = 3,
                            ProductionLineId = new Guid("88888888-aaaa-bbbb-cccc-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-bbbb-cccc-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Arm modules",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Robot Arm Assembly",
                            OrdinalNumber = 1,
                            ProductionLineId = new Guid("99999999-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("44444444-bbbb-cccc-dddd-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Servo motors",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Motor Assembly",
                            OrdinalNumber = 2,
                            ProductionLineId = new Guid("99999999-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("44444444-cccc-dddd-eeee-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Safety certification",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Safety Check",
                            OrdinalNumber = 3,
                            ProductionLineId = new Guid("99999999-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-bbbb-cccc-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Initial calibration",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Calibration Base",
                            OrdinalNumber = 1,
                            ProductionLineId = new Guid("aaaaaaaa-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-bbbb-cccc-dddd-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Camera alignment",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vision Alignment",
                            OrdinalNumber = 2,
                            ProductionLineId = new Guid("aaaaaaaa-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-cccc-dddd-eeee-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mechanical testing",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stress Test",
                            OrdinalNumber = 3,
                            ProductionLineId = new Guid("aaaaaaaa-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-bbbb-cccc-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "PCB assembly",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AGV Control Board",
                            OrdinalNumber = 1,
                            ProductionLineId = new Guid("bbbbbbbb-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-bbbb-cccc-dddd-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sensors installation",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lidar Install",
                            OrdinalNumber = 2,
                            ProductionLineId = new Guid("bbbbbbbb-aaaa-bbbb-cccc-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-cccc-dddd-eeee-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AGV nav calibration",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Navigation Test",
                            OrdinalNumber = 3,
                            ProductionLineId = new Guid("bbbbbbbb-aaaa-bbbb-cccc-222222222222")
                        });
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.Factory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Factories", "cell_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Industrial Park 12",
                            City = "Budapest",
                            Country = "Hungary",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@mainfactory.hu",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Main Factory",
                            Phone = "+36 1 555 1234"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Technológia u. 4.",
                            City = "Győr",
                            Country = "Hungary",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@backupplant.hu",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Backup Plant",
                            Phone = "+36 96 444 777"
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-bbbb-cccc-111111111111"),
                            Address = "Werkstrasse 8",
                            City = "Stuttgart",
                            Country = "Germany",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@electronicsplant.de",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electronics Plant",
                            Phone = "+49 711 123 456"
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-bbbb-cccc-222222222222"),
                            Address = "Technicka 22",
                            City = "Brno",
                            Country = "Czech Republic",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@automationhub.cz",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automation Hub",
                            Phone = "+420 555 987 654"
                        });
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("ProductionLines", "cell_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automotive ECU assembly line",
                            FactoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Assembly Line A",
                            OrdinalNumber = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Battery module production",
                            FactoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Assembly Line B",
                            OrdinalNumber = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Final packaging and quality control",
                            FactoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packaging Line 1",
                            OrdinalNumber = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Motherboard soldering and assembly",
                            FactoryId = new Guid("33333333-aaaa-bbbb-cccc-111111111111"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PCB Line 1",
                            OrdinalNumber = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-density PCB assembly",
                            FactoryId = new Guid("33333333-aaaa-bbbb-cccc-111111111111"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PCB Line 2",
                            OrdinalNumber = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electronic unit final assembly",
                            FactoryId = new Guid("33333333-aaaa-bbbb-cccc-111111111111"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Final Assembly Line",
                            OrdinalNumber = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-aaaa-bbbb-cccc-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Industrial robot assembly",
                            FactoryId = new Guid("44444444-aaaa-bbbb-cccc-222222222222"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automation Line 1",
                            OrdinalNumber = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-bbbb-cccc-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Robot calibration and testing line",
                            FactoryId = new Guid("44444444-aaaa-bbbb-cccc-222222222222"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automation Line 2",
                            OrdinalNumber = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-aaaa-bbbb-cccc-222222222222"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AGV control unit production",
                            FactoryId = new Guid("44444444-aaaa-bbbb-cccc-222222222222"),
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Automation Line 3",
                            OrdinalNumber = 9,
                            Status = 2
                        });
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.WorkStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MqttDeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.ToTable("WorkStations", "cell_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CellId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manual soldering station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A1",
                            Name = "WS-SLD-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CellId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated soldering robot arm",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A2",
                            Name = "WS-SLD-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CellId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Precision soldering microstation",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A3",
                            Name = "WS-SLD-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CellId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-temperature soldering unit",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A4",
                            Name = "WS-SLD-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CellId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flux application station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A5",
                            Name = "WS-SLD-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CellId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reflow soldering preparation",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A6",
                            Name = "WS-SLD-06",
                            OrdinalNumber = 6
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CellId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Post-soldering cooling point",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A7",
                            Name = "WS-SLD-07",
                            OrdinalNumber = 7
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CellId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Visual inspection camera station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A8",
                            Name = "WS-INS-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CellId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AOI optical scan unit",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A9",
                            Name = "WS-INS-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CellId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated dimension check sensor",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A10",
                            Name = "WS-INS-04",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CellId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Barcode and label verification",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A11",
                            Name = "WS-INS-05",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CellId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quality classification station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A12",
                            Name = "WS-INS-06",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CellId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-resolution defect camera",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A13",
                            Name = "WS-INS-03",
                            OrdinalNumber = 6
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Box assembly station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A14",
                            Name = "WS-PKG-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Filling alignment station",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A15",
                            Name = "WS-PKG0-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Protective foam insertion unit",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A16",
                            Name = "WS-PKG0-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated box sealing",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A17",
                            Name = "WS-PKG0-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Package weight verification",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A18",
                            Name = "WS-PKG0-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated carton forming",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A19",
                            Name = "WS-PKG0-01",
                            OrdinalNumber = 6
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated box printing",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A20",
                            Name = "WS-PKG1-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RFID label application",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A21",
                            Name = "WS-PKG1-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated shrink-wrap tunnel",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A22",
                            Name = "WS-PKG1-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Parcel integrity check",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A23",
                            Name = "WS-PKG1-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sorting conveyor loader",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A24",
                            Name = "WS-PKG1-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tape dispensing system",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A25",
                            Name = "WS-PKG2-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated barcode printer",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A26",
                            Name = "WS-PKG2-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Package photo capture unit",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A27",
                            Name = "WS-PKG2-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Load distribution analyzer",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A28",
                            Name = "WS-PKG2-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Outgoing product staging",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A29",
                            Name = "WS-PKG2-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Box folding robot arm",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A30",
                            Name = "WS-PKG3-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Label placement verification",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A31",
                            Name = "WS-PKG3-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Box pressure test unit",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A32",
                            Name = "WS-PKG3-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automated strapping machine",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A33",
                            Name = "WS-PKG3-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666665"),
                            CellId = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Final pallet loading spot",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "A34",
                            Name = "WS-PKG3-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("10000000-aaaa-bbbb-cccc-111111111111"),
                            CellId = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solder prep station #1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B1",
                            Name = "WS-SP-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-aaaa-bbbb-cccc-111111111112"),
                            CellId = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solder prep station #2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B2",
                            Name = "WS-SP-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-aaaa-bbbb-cccc-111111111113"),
                            CellId = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solder prep station #3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B3",
                            Name = "WS-SP-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("10000000-aaaa-bbbb-cccc-111111111114"),
                            CellId = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solder prep station #4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B4",
                            Name = "WS-SP-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("10000000-aaaa-bbbb-cccc-111111111115"),
                            CellId = new Guid("11111111-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solder prep station #5",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B5",
                            Name = "WS-SP-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("20000000-aaaa-bbbb-cccc-111111111111"),
                            CellId = new Guid("11111111-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wave solder #1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B6",
                            Name = "WS-SLD-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-aaaa-bbbb-cccc-111111111112"),
                            CellId = new Guid("11111111-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wave solder #2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B7",
                            Name = "WS-SLD-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-aaaa-bbbb-cccc-111111111113"),
                            CellId = new Guid("11111111-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wave solder #3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B8",
                            Name = "WS-SLD-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-aaaa-bbbb-cccc-111111111114"),
                            CellId = new Guid("11111111-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wave solder #4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B9",
                            Name = "WS-SLD-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-aaaa-bbbb-cccc-111111111115"),
                            CellId = new Guid("11111111-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wave solder #5",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B10",
                            Name = "WS-SLD-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("30000000-aaaa-bbbb-cccc-111111111111"),
                            CellId = new Guid("11111111-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cleaning station #1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B11",
                            Name = "WS-CLN-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-aaaa-bbbb-cccc-111111111112"),
                            CellId = new Guid("11111111-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cleaning station #2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B12",
                            Name = "WS-CLN-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-aaaa-bbbb-cccc-111111111113"),
                            CellId = new Guid("11111111-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cleaning station #3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B13",
                            Name = "WS-CLN-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-aaaa-bbbb-cccc-111111111114"),
                            CellId = new Guid("11111111-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cleaning station #4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B14",
                            Name = "WS-CLN-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("30000000-aaaa-bbbb-cccc-111111111115"),
                            CellId = new Guid("11111111-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cleaning station #5",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "B15",
                            Name = "WS-CLN-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("40000000-aaaa-bbbb-cccc-111111111111"),
                            CellId = new Guid("22222222-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pick&Place #1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "D1",
                            Name = "WS-PP-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-aaaa-bbbb-cccc-111111111112"),
                            CellId = new Guid("22222222-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pick&Place #2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "D2",
                            Name = "WS-PP-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-aaaa-bbbb-cccc-111111111113"),
                            CellId = new Guid("22222222-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pick&Place #3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "D3",
                            Name = "WS-PP-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-aaaa-bbbb-cccc-111111111114"),
                            CellId = new Guid("22222222-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pick&Place #4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "D4",
                            Name = "WS-PP-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-aaaa-bbbb-cccc-111111111115"),
                            CellId = new Guid("22222222-aaaa-bbbb-cccc-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pick&Place #5",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "D5",
                            Name = "WS-PP-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("50000000-aaaa-bbbb-cccc-111111111111"),
                            CellId = new Guid("22222222-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reflow oven #1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "E1",
                            Name = "WS-RF-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-aaaa-bbbb-cccc-111111111112"),
                            CellId = new Guid("22222222-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reflow oven #2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "E2",
                            Name = "WS-RF-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-aaaa-bbbb-cccc-111111111113"),
                            CellId = new Guid("22222222-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reflow oven #3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "E3",
                            Name = "WS-RF-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-aaaa-bbbb-cccc-111111111114"),
                            CellId = new Guid("22222222-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reflow oven #4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "E4",
                            Name = "WS-RF-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("50000000-aaaa-bbbb-cccc-111111111115"),
                            CellId = new Guid("22222222-bbbb-cccc-dddd-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reflow oven #5",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "E5",
                            Name = "WS-RF-05",
                            OrdinalNumber = 5
                        },
                        new
                        {
                            Id = new Guid("60000000-aaaa-bbbb-cccc-111111111111"),
                            CellId = new Guid("22222222-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AOI scanner #1",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "F1",
                            Name = "WS-AOI-01",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-aaaa-bbbb-cccc-111111111112"),
                            CellId = new Guid("22222222-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AOI scanner #2",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "F2",
                            Name = "WS-AOI-02",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            Id = new Guid("60000000-aaaa-bbbb-cccc-111111111113"),
                            CellId = new Guid("22222222-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AOI scanner #3",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "F3",
                            Name = "WS-AOI-03",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            Id = new Guid("60000000-aaaa-bbbb-cccc-111111111114"),
                            CellId = new Guid("22222222-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AOI scanner #4",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "F4",
                            Name = "WS-AOI-04",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            Id = new Guid("60000000-aaaa-bbbb-cccc-111111111115"),
                            CellId = new Guid("22222222-cccc-dddd-eeee-111111111111"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AOI scanner #5",
                            IsDeleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MqttDeviceId = "F5",
                            Name = "WS-AOI-05",
                            OrdinalNumber = 5
                        });
                });

            modelBuilder.Entity("CellTracker.Api.Models.OperatorTask.OperatorTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityGoal")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkStationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkStationId")
                        .IsUnique();

                    b.ToTable("OperatorTasks", "cell_tracker");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Simulation.SimulationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MinutesOfSimulation")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfProductsMade")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Shift")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("Simulations", "cell_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MinutesOfSimulation = 1,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfProductsMade = 145,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Shift = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MinutesOfSimulation = 2,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfProductsMade = 198,
                            ProductionLineId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Shift = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MinutesOfSimulation = 3,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfProductsMade = 170,
                            ProductionLineId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Shift = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MinutesOfSimulation = 4,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfProductsMade = 220,
                            ProductionLineId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Shift = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MinutesOfSimulation = 5,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfProductsMade = 260,
                            ProductionLineId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Shift = 1
                        });
                });

            modelBuilder.Entity("CellTracker.Api.Auth.RefreshToken", b =>
                {
                    b.HasOne("CellTracker.Api.Auth.SiteUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.Cell", b =>
                {
                    b.HasOne("CellTracker.Api.Models.Configuration.ProductionLine", "ProductionLine")
                        .WithMany("Cells")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.ProductionLine", b =>
                {
                    b.HasOne("CellTracker.Api.Models.Configuration.Factory", "Factory")
                        .WithMany("ProductionLines")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.WorkStation", b =>
                {
                    b.HasOne("CellTracker.Api.Models.Configuration.Cell", "Cell")
                        .WithMany("WorkStations")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("CellTracker.Api.Models.OperatorTask.OperatorTask", b =>
                {
                    b.HasOne("CellTracker.Api.Models.Configuration.WorkStation", "WorkStation")
                        .WithOne("OperatorTask")
                        .HasForeignKey("CellTracker.Api.Models.OperatorTask.OperatorTask", "WorkStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkStation");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Simulation.SimulationModel", b =>
                {
                    b.HasOne("CellTracker.Api.Models.Configuration.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.Cell", b =>
                {
                    b.Navigation("WorkStations");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.Factory", b =>
                {
                    b.Navigation("ProductionLines");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.ProductionLine", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("CellTracker.Api.Models.Configuration.WorkStation", b =>
                {
                    b.Navigation("OperatorTask");
                });
#pragma warning restore 612, 618
        }
    }
}
